### ISSUE TITLE
0x5c886B3Ed9fb762f1eB55EB98c00df4D3cF63322

### ISSUE THREAD

**Issue by ticketid** [safe-global/safe-user-allocation-reports#111] opened 2022-09-08 17:33 UTC
# Related Safe Addresses

list:
0xbee4eaef515072c41b23cbe937d48d8207de2e32
0x8dfd1f84cf9d29b4aaf6b2baf1c509164f73473e
0x8a368801a9a08a6e979978c6b831befa7b30f0ad
0x88e79af0c051a0cd0dda7138f647e0377c907e61
0x6b00e0465b7f2c45a0160d9ba1e301182caf2c26
0x4990a1ba078ac31eb955b1285516bc4e391f0e5e
0x45fc0f37fed5a45ee35287abb8ab95f33c7a51ed
0x45c3e85c6586501883141f7e33165cd5d19a9c9a
0x2db6320c647fe6af6ef096523387e43efc7ebe35
0x112efae30e371e43ff9719965048bff70f519e1c

Full List
"https://etherscan.io/txs?a=0x5c886b3ed9fb762f1eb55eb98c00df4d3cf63322&p=11"
-->

# Reasoning

<Addresses are frequently created safe, but tokens are not deposited into the safe
-->

# Methodology

# Safe Address

**Comment by tschubotz** [comment] 2022-09-09 15:41
duplicate of #109 it seems

**Closed by tschubotz** 2022-09-09 15:41 UTC
